In [0]:
import numpy as np
import pandas as pd

In [0]:
d=pd.read_csv('Iris.csv')

In [151]:
d.head(10)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa

In [152]:
d.info

<bound method DataFrame.info of       Id  SepalLengthCm  ...  PetalWidthCm         Species
0      1            5.1  ...           0.2     Iris-setosa
1      2            4.9  ...           0.2     Iris-setosa
2      3            4.7  ...           0.2     Iris-setosa
3      4            4.6  ...           0.2     Iris-setosa
4      5            5.0  ...           0.2     Iris-setosa
..   ...            ...  ...           ...             ...
145  146            6.7  ...           2.3  Iris-virginica
146  147            6.3  ...           1.9  Iris-virginica
147  148            6.5  ...           2.0  Iris-virginica
148  149            6.2  ...           2.3  Iris-virginica
149  150            5.9  ...           1.8  Iris-virginica

[150 rows x 6 columns]>

In [89]:
d['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [0]:
d['Species'].replace(str('Iris-setosa'),0,inplace=True)
d['Species'].replace(str('Iris-versicolor'),1,inplace=True)
d['Species'].replace(str('Iris-virginica'),2,inplace=True)

In [91]:
d.head(10)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        0
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0
3   4            4.6           3.1            1.5           0.2        0
4   5            5.0           3.6            1.4           0.2        0
5   6            5.4           3.9            1.7           0.4        0
6   7            4.6           3.4            1.4           0.3        0
7   8            5.0           3.4            1.5           0.2        0
8   9            4.4           2.9            1.4           0.2        0
9  10            4.9           3.1            1.5           0.1        0

In [92]:
d['Species'].unique()

array([0, 1, 2])

In [93]:
d['Species'].astype(int)

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Species, Length: 150, dtype: int64

In [94]:
d.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species            int64
dtype: object

In [0]:
x=d[['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']]
y=d['Species']

In [0]:
from sklearn.model_selection import train_test_split
x1,x2,y1,y2=train_test_split(x,y,test_size=0.3,random_state=42)

In [99]:
print(x1)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
81             5.5           2.4            3.7           1.0
133            6.3           2.8            5.1           1.5
137            6.4           3.1            5.5           1.8
75             6.6           3.0            4.4           1.4
109            7.2           3.6            6.1           2.5
..             ...           ...            ...           ...
71             6.1           2.8            4.0           1.3
106            4.9           2.5            4.5           1.7
14             5.8           4.0            1.2           0.2
92             5.8           2.6            4.0           1.2
102            7.1           3.0            5.9           2.1

[105 rows x 4 columns]


In [0]:
x1=np.array(x1).reshape(-1,4)
y1=np.array(y1).reshape(-1,1)

In [101]:
x1.shape

(105, 4)

In [102]:
y1.shape

(105, 1)

In [189]:
from sklearn import svm
s=svm.SVC(kernel='linear')
s.fit(x1,y1)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [0]:
pred=s.predict(x2)

In [191]:
print(pred)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0 0 0 2 1 1 0 0]


In [169]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y2, pred))

Accuracy: 1.0


In [170]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y2, pred))
print(classification_report(y2, pred))

[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [172]:
print("co-efficients : ",s.coef_)
print("Intercept : ",s.intercept_)

co-efficients :  [[-0.04631136  0.52105578 -1.0030165  -0.46411816]
 [-0.00641373  0.17867392 -0.5389119  -0.29158729]
 [ 0.57613513  1.19215085 -2.03465638 -1.67923323]]
Intercept :  [1.45338269 1.50537328 5.76365067]


In [192]:
from sklearn import svm
s1=svm.SVC(kernel='poly')
s1.fit(x1,y1)
y_=s1.predict(x2)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [193]:
print('Accuracy : %.2f' %metrics.accuracy_score(y_,y2))

Accuracy : 0.98


In [156]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y2, pred))
print(classification_report(y2, y_))

[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.92      0.96        13
           2       0.93      1.00      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.97        45
weighted avg       0.98      0.98      0.98        45



In [0]:
from sklearn.linear_model import LogisticRegression

In [174]:
L=LogisticRegression()
L.fit(x1,y1)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
y_pred1=L.predict(x2)

In [176]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y2,y_pred1))

Accuracy: 1.0


In [177]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y2, pred))
print(classification_report(y2,y_pred1))

[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [179]:
print("co-efficients : ",L.coef_)
print("Intercept : ",L.intercept_)

co-efficients :  [[-0.40467861  0.86071942 -2.28126141 -0.96724374]
 [ 0.46614353 -0.36969427 -0.18638736 -0.71325556]
 [-0.06146492 -0.49102514  2.46764877  1.68049931]]
Intercept :  [  8.90744661   2.18302894 -11.09047555]


In [0]:
from sklearn.neighbors import KNeighborsClassifier  
clf=KNeighborsClassifier(n_neighbors=10) 

In [163]:
clf.fit(x1,y1)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  """Entry point for launching an IPython kernel.


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                     weights='uniform')

In [0]:
y__=clf.predict(x2)

In [165]:
from sklearn.metrics import accuracy_score
print('Accuracy: %.2f'% accuracy_score(y2,y22))

Accuracy: 1.00


In [166]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y2, pred))
print(classification_report(y2,y__))

[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [0]:
from sklearn.linear_model import Perceptron

In [195]:
p=Perceptron()
p.fit(x1,y1)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=1.0,
           fit_intercept=True, max_iter=1000, n_iter_no_change=5, n_jobs=None,
           penalty=None, random_state=0, shuffle=True, tol=0.001,
           validation_fraction=0.1, verbose=0, warm_start=False)

In [0]:
yu=p.predict(x2)

In [197]:
from sklearn.metrics import accuracy_score
print("Accuracy : %.2f" % 
      accuracy_score(yu,y2))

Accuracy : 0.80


In [198]:
print(p.coef_)

[[  1.    4.7  -7.5  -2.8]
 [ 14.7 -31.9   8.1 -25.2]
 [-29.2 -30.2  56.6  47.6]]


In [199]:
print(p.intercept_)

[  1.  14. -21.]


In [200]:
print(yu)

[2 0 2 2 2 0 1 2 2 1 2 0 0 0 0 2 2 1 2 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 2
 0 0 0 2 2 2 0 0]
